<?xml version="1.0" encoding="utf-8"?><Database Name="db" Class="DCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=GOODMANMAIN\SQLEXPRESS;Initial Catalog=db;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ApplicationServices" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Project" Member="Project">
    <Type Name="Project">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DataStart" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DataEnd" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Project_EmployeeProject" Member="EmployeeProject" ThisKey="Id" OtherKey="ProjectId" Type="EmployeeProject" />
    </Type>
  </Table>
  <Table Name="dbo.Position" Member="Position">
    <Type Name="Position">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Position_EmployeeProject" Member="EmployeeProject" ThisKey="Id" OtherKey="PositionId" Type="EmployeeProject" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeProject" Member="EmployeeProject">
    <Type Name="EmployeeProject">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountDaysWork" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OfficialSalary" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PositionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Position_EmployeeProject" Member="Position" ThisKey="PositionId" OtherKey="Id" Type="Position" IsForeignKey="true" />
      <Association Name="Project_EmployeeProject" Member="Project" ThisKey="ProjectId" OtherKey="Id" Type="Project" IsForeignKey="true" />
      <Association Name="Employee_EmployeeProject" Member="Employee" ThisKey="EmployeeId" OtherKey="Id" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employee">
    <Type Name="Employee">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Patronymic" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Characterization" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AvatarName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Employee_EmployeeProject" Member="EmployeeProject" ThisKey="Id" OtherKey="EmployeeId" Type="EmployeeProject" />
    </Type>
  </Table>
</Database>