using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Lab4
{
    public partial class EmployeesProjects : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!User.IsInRole("Admin")) return;
            GridView1.AutoGenerateDeleteButton = true;
            GridView1.AutoGenerateEditButton = true;
            GridView1.AutoGenerateSelectButton = true;
            DetailsView1.Visible = true;
        }

        protected void DetailsView1_ItemInserted(object sender, DetailsViewInsertedEventArgs e)
        {
            GridView1.DataBind();
        }

        protected void DetailsView1_ItemUpdated(object sender, DetailsViewUpdatedEventArgs e)
        {
            GridView1.DataBind();
        }

        protected void DetailsView1_ItemDeleted(object sender, DetailsViewDeletedEventArgs e)
        {
            GridView1.DataBind();
        }

        protected void SqlDataSource1_Selecting(object sender, SqlDataSourceSelectingEventArgs e)
        {

        }

        protected void DropDownList1_SelectedIndexChanged(object sender, EventArgs e)
        {
        }

        protected void Button2_Click(object sender, EventArgs e)
        {
            Panel1.Visible = true;
            Button2.Visible = false;
            CreateB.Visible = true;
            UpdateB.Visible = false;
            DetailsView1.Visible = false;
            Panel2.Visible = false;
        }

        protected void Button1_Click(object sender, EventArgs e)
        {
            var empP = new EmployeeProject()
                           {
                               CountDaysWork = int.Parse(CountDaysWorkTB.Text),
                               OfficialSalary = int.Parse(OfficialSalaryTB.Text),
                               EmployeeId = int.Parse(EmployeesDDL.SelectedValue),
                               ProjectId = int.Parse(ProjectsDDL.SelectedValue),
                               PositionId = int.Parse(PositionsDDL.SelectedValue),
                           };
            var db = new DCDataContext();
            db.EmployeeProject.InsertOnSubmit(empP);
            db.SubmitChanges();
            Response.Redirect("EmployeesProjects.aspx");
        }

        protected void UpdateLB_Click(object sender, EventArgs e)
        {
            Panel1.Visible = true;
            DetailsView1.Visible = false;
            var db = new DCDataContext();
            var empP = db.EmployeeProject.Single(a => a.Id == (int)DetailsView1.SelectedValue);
            EmployeesDDL.DataBind();
            EmployeesDDL.SelectedIndex =
                EmployeesDDL.Items.IndexOf(EmployeesDDL.Items.OfType<ListItem>().Single(a => a.Value == empP.EmployeeId.ToString()));
            PositionsDDL.DataBind();
            PositionsDDL.SelectedIndex =
                PositionsDDL.Items.IndexOf(PositionsDDL.Items.OfType<ListItem>().Single(a => a.Value == empP.PositionId.ToString()));
            ProjectsDDL.DataBind();
            ProjectsDDL.SelectedIndex =
                ProjectsDDL.Items.IndexOf(ProjectsDDL.Items.OfType<ListItem>().Single(a => a.Value == empP.ProjectId.ToString()));
            OfficialSalaryTB.Text = empP.OfficialSalary.ToString();
            CountDaysWorkTB.Text = empP.CountDaysWork.ToString();
            CreateB.Visible = false;
            UpdateB.Visible = true;
        }

        protected void UpdateB_Click(object sender, EventArgs e)
        {
            var db = new DCDataContext();
            var empP = db.EmployeeProject.Single(a => a.Id == (int)DetailsView1.SelectedValue);
            empP.CountDaysWork = int.Parse(CountDaysWorkTB.Text);
            empP.OfficialSalary = int.Parse(OfficialSalaryTB.Text);
            empP.EmployeeId = int.Parse(EmployeesDDL.SelectedValue);
            empP.ProjectId = int.Parse(ProjectsDDL.SelectedValue);
            empP.PositionId = int.Parse(PositionsDDL.SelectedValue);
            db.SubmitChanges();
            Response.Redirect("EmployeesProjects.aspx");
        }

        protected void DeleteLB_Click(object sender, EventArgs e)
        {
            var db = new DCDataContext();
            var empP = db.EmployeeProject.Single(a => a.Id == (int)DetailsView1.SelectedValue);
            db.EmployeeProject.DeleteOnSubmit(empP);
            db.SubmitChanges();
            Response.Redirect("EmployeesProjects.aspx");
        }
    }
}